// sample response for /eng/school/n8276720/translate
const a = {
  eng: 'school',
  fin: 'koulu',
  fas: 'مدرسه',
  fry: 'skoalle',
  goh: 'scuola',
  pus: 'ښوونځى',
  kir: 'мектеп',
  ang: 'scol',
  vol: 'jul',
  fao: 'skúli',
  spa: 'escuela',
  ron: 'şcoală',
  slk: 'škola',
  glv: 'schoill',
  bel: 'школа',
  tam: 'பள்ளி',
  epo: 'lernejo',
  nap: 'scola',
  cic: 'holisso pisa chi',
  swe: 'skola',
  ewe: 'suku',
  san: 'विद्यालय',
  lav: 'skola',
  ita: 'scuola',
  slv: 'šola',
  sqi: 'shkollë',
  urd: 'سکول',
  kat: 'სკოლა',
  tgl: 'eskwelahan',
  sot: 'sekolo',
  smn: 'škovlâ',
  sme: 'skuvla',
  nld: 'school',
  yid: 'שולע',
  hye: 'ուսումնարան',
  zsm: 'maktab',
  dan: 'skole',
  nob: 'skole',
  hbs: 'škola',
  ben: 'স্কুল',
  deu: 'Schulunterricht',
  tur: 'mektep',
  rus: 'школа',
  vie: 'trường học',
  ltz: 'Schoul',
  tgk: 'мактаб',
  est: 'kool',
  nan: '學校',
  kal: 'atuarfik',
  nor: 'skole',
  swh: 'shule',
  hat: 'lekòl',
  sga: 'scol',
  zul: 'isikole',
  xcl: 'դպրոց',
  hun: 'iskola',
  que: 'yachay wasi',
  ell: 'σχολείο',
  por: 'escolas',
  pol: 'szkoła',
  fra: 'établissement scolaire',
  ces: 'škola',
  lad: 'סקורה',
  cor: 'skol',
  crh: 'mektep',
  eus: 'eskola; ikastetxe',
  jpn: '学校',
  ido: 'skolo',
  bul: 'училище',
  tet: 'eskola',
  gle: 'scoil',
  fil: 'paaralan',
  syc: 'ܡܕܪܫܬܐ',
  afr: 'skool',
  xho: 'isikolo',
  lao: 'ໂຮງຮຽນ',
  sco: 'schuil',
  aze: 'мәктәб',
  isl: 'skóli',
  heb: 'בית ספר',
  mya: 'ကျောင်း',
  lit: 'pamokos',
  srp: 'школа',
};
