// sample response for /eng/school
[
  {
    definitions: [
      'swim in or form a large group of fish; "A cluster of schooling fish was attracted to the bait"',
      'the process of being formally educated at a school; "what will you do when you finish school?"',
      'the period of instruction in a school; the time period when school is in session; "stay after school"; "he didn\'t miss a single day of school"; "when the school day was done we would walk home together"',
      'teach or refine to be discriminative in taste or judgment; "Cultivate your musical taste"; "Train your tastebuds"; "She is well schooled in poetry"',
      'a large group of fish; "a school of small glittering fish swam by"',
      'an educational institution; "the school was founded in 1900"',
      'educate in or as if in a school; "The children are schooled at great cost to their parents in private institutions"',
      'a building where young people receive education; "the school was built in 1932"; "he walked to school every morning"',
      'a body of creative artists or writers or thinkers linked by a similar style or by similar teachers; "the Venetian school of painting"',
      'an educational institution\'s faculty and students; "the school keeps parents informed"; "the whole school turned out for the game"',
      'a body of creative artists or writers or thinkers linked by a similar style or by similar teachers; "the Venetian school of painting"',
      'teach and supervise (someone); act as a trainer or coach (to), as in sports; "He is training our Olympic team"; "She is coaching the crew"',
      'a complex of buildings in which an institution of higher education is housed',
      'the body of faculty and students at a university',
      'an educational institution; "the school was founded in 1900"',
      "a school in a university offering study leading to degrees beyond the bachelor's degree",
      'a school for young children; usually the first 6 or 8 grades',
      'a building where young people receive education; "the school was built in 1932"; "he walked to school every morning"',
      'create by training and teaching; "The old master is training world-class violinists"; "we develop the leaders for the future"',
      'an institution of higher education created to educate and grant degrees; often a part of a university',
    ],
  },
  {
    parts_of_speech: [
      'verb',
      'noun',
      'noun',
      'verb',
      'noun',
      'noun',
      'verb',
      'noun',
      'noun',
      'noun',
      'noun',
      'verb',
      'noun',
      'noun',
      'noun',
      'noun',
      'noun',
      'noun',
      'verb',
      'noun',
    ],
  },
  {
    synsets: [
      's/v1961334',
      's/n5757536',
      's/n15203229',
      's/v2388403',
      's/n7995453',
      's/n8276720',
      's/v2387910',
      's/n4146050',
      's/n8275185',
      's/n8277393',
      's/n8275185',
      's/v833702',
      's/n3069752',
      's/n8286163',
      's/n8276720',
      's/n8282696',
      's/n8412749',
      's/n4146050',
      's/v603298',
      's/n8278324',
    ],
  },
];
